---
abstract: 'Mojo interface to S3 objects.'
author:
  - 'Scott Kiehn E<lt>sk.keenlinks@gmail.comE<gt>'
build_requires:
  Test::Exception: '0.43'
  Test::More: '1.302075'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.022, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-S3Object
provides:
  Mojo::S3Object:
    file: lib/Mojo/S3Object.pm
    version: 0.02_3
requires:
  Mojolicious: '6.00'
  perl: '5.008001'
version: 0.02_3
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
